<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /* 
            [
                'name'=>'roles.index',
                'guard_name'=>'web',
                'master_name'=>'roles'
            ],
            [
                'name'=>'roles.create',
                'guard_name'=>'web',
                'master_name'=>'roles'
            ],
            [
                'name'=>'roles.edit',
                'guard_name'=>'web',
                'master_name'=>'roles'
            ],
            [
                'name'=>'role.destroy',
                'guard_name'=>'web',
                'master_name'=>'roles'
            ],

            [
                'name'=>'users.index',
                'guard_name'=>'web',
                'master_name'=>'users'
            ],
            [
                'name'=>'users.create',
                'guard_name'=>'web',
                'master_name'=>'users'
            ],
            [
                'name'=>'users.edit',
                'guard_name'=>'web',
                'master_name'=>'users'
            ],
            [
                'name'=>'users.destroy',
                'guard_name'=>'web',
                'master_name'=>'users'
            ],
            [
                'name'=>'category.index',
                'guard_name'=>'web',
                'master_name'=>'category'
            ],
            [
                'name'=>'category.create',
                'guard_name'=>'web',
                'master_name'=>'category'
            ],
            [
                'name'=>'category.edit',
                'guard_name'=>'web',
                'master_name'=>'category'
            ],
            [
                'name'=>'category.destroy',
                'guard_name'=>'web',
                'master_name'=>'category'
            ], 
            [
                'name'=>'hsn.index',
                'guard_name'=>'web',
                'master_name'=>'hsn'
            ],
            [
                'name'=>'hsn.create',
                'guard_name'=>'web',
                'master_name'=>'hsn'
            ],
            [
                'name'=>'hsn.edit',
                'guard_name'=>'web',
                'master_name'=>'hsn'
            ],
            [
                'name'=>'hsn.destroy',
                'guard_name'=>'web',
                'master_name'=>'hsn'
            ],
            [
                'name'=>'gst.index',
                'guard_name'=>'web',
                'master_name'=>'gst'
            ],
            [
                'name'=>'gst.create',
                'guard_name'=>'web',
                'master_name'=>'gst'
            ],
            [
                'name'=>'gst.edit',
                'guard_name'=>'web',
                'master_name'=>'gst'
            ],
            [
                'name'=>'gst.destroy',
                'guard_name'=>'web',
                'master_name'=>'gst'
            ],
            [
                'name'=>'item.index',
                'guard_name'=>'web',
                'master_name'=>'item'
            ],
            [
                'name'=>'item.create',
                'guard_name'=>'web',
                'master_name'=>'item'
            ],
            [
                'name'=>'item.edit',
                'guard_name'=>'web',
                'master_name'=>'item'
            ],
            [
                'name'=>'item.destroy',
                'guard_name'=>'web',
                'master_name'=>'item'
            ],
            [
                'name'=>'stocks.index',
                'guard_name'=>'web',
                'master_name'=>'stocks'
            ],
            [
                'name'=>'stocks.create',
                'guard_name'=>'web',
                'master_name'=>'stocks'
            ],
            [
                'name'=>'stocks.edit',
                'guard_name'=>'web',
                'master_name'=>'stocks'
            ],
            [
                'name'=>'stocks.destroy',
                'guard_name'=>'web',
                'master_name'=>'stocks'
            ],
            [
                'name'=>'vendors.index',
                'guard_name'=>'web',
                'master_name'=>'vendors'
            ],
            [
                'name'=>'vendors.create',
                'guard_name'=>'web',
                'master_name'=>'vendors'
            ],
            [
                'name'=>'vendors.edit',
                'guard_name'=>'web',
                'master_name'=>'vendors'
            ],
            [
                'name'=>'vendors.destroy',
                'guard_name'=>'web',
                'master_name'=>'vendors'
            ]
            ,[
                'name'=>'invoice.master',
                'guard_name'=>'web',
                'master_name'=>'master'
            ],
            [
                'name'=>'stock-distributions.index',
                'guard_name'=>'web',
                'master_name'=>'stock-distribution'
            ],
            [
                'name'=>'stock-distributions.create',
                'guard_name'=>'web',
                'master_name'=>'stock-distribution'
            ],
            [
                'name'=>'stock-distributions.show',
                'guard_name'=>'web',
                'master_name'=>'stock-distribution'
            ],
            [
                'name'=>'stock-distributions.destroy',
                'guard_name'=>'web',
                'master_name'=>'stock-distribution'
            ],[
                'name'=>'users-stock.list',
                'guard_name'=>'web',
                'master_name'=>'users-stock'
            ],
            [
                'name'=>'local-stock-distribution.create',
                'guard_name'=>'web',
                'master_name'=>'local-stock-distribution'
            ],[
                'name'=>'local-stock-distribution.show',
                'guard_name'=>'web',
                'master_name'=>'local-stock-distribution'
            ],
            [
                'name'=>'local-stock-distribution.destroy',
                'guard_name'=>'web',
                'master_name'=>'local-stock-distribution'
            ],
            [
                'name'=>'stock-distributions.store',
                'guard_name'=>'web',
                'master_name'=>'stock-distribution'
            ],
            [
                'name'=>'vendors.store',
                'guard_name'=>'web',
                'master_name'=>'vendors'
            ],
            [
                'name'=>'vendors.update',
                'guard_name'=>'web',
                'master_name'=>'vendors'
            ],
            [
                'name'=>'stocks.store',
                'guard_name'=>'web',
                'master_name'=>'stocks'
            ],
            [
                'name'=>'stocks.update',
                'guard_name'=>'web',
                'master_name'=>'stocks'
            ],
            [
                'name'=>'item.store',
                'guard_name'=>'web',
                'master_name'=>'item'
            ],
            [
                'name'=>'item.update',
                'guard_name'=>'web',
                'master_name'=>'item'
            ],
            [
                'name'=>'gst.store',
                'guard_name'=>'web',
                'master_name'=>'gst'
            ],
            [
                'name'=>'gst.update',
                'guard_name'=>'web',
                'master_name'=>'gst'
            ],
            [
                'name'=>'hsn.store',
                'guard_name'=>'web',
                'master_name'=>'hsn'
            ],
            [
                'name'=>'hsn.update',
                'guard_name'=>'web',
                'master_name'=>'hsn'
            ],
            [
                'name'=>'category.store',
                'guard_name'=>'web',
                'master_name'=>'category'
            ],
            [
                'name'=>'category.update',
                'guard_name'=>'web',
                'master_name'=>'category'
            ],
            [
                'name'=>'users.store',
                'guard_name'=>'web',
                'master_name'=>'users'
            ],
            [
                'name'=>'users.update',
                'guard_name'=>'web',
                'master_name'=>'users'
            ],
            [
                'name'=>'roles.store',
                'guard_name'=>'web',
                'master_name'=>'roles'
            ],
            [
                'name'=>'roles.update',
                'guard_name'=>'web',
                'master_name'=>'roles'
            ],[
                'name'=>'local-stock-distribution.store',
                'guard_name'=>'web',
                'master_name'=>'local-stock-distribution'
            ],[
                'name'=>'expenses.index',
                'guard_name'=>'web',
                'master_name'=>'expenses'
            ],
            [
                'name'=>'expenses.store',
                'guard_name'=>'web',
                'master_name'=>'expenses'
            ],
            [
                'name'=>'expenses.edit',
                'guard_name'=>'web',
                'master_name'=>'expenses'
            ],
            [
                'name'=>'expenses.update',
                'guard_name'=>'web',
                'master_name'=>'expenses'
            ],
            [
                'name'=>'expenses.destroy',
                'guard_name'=>'web',
                'master_name'=>'expenses'
            ],
            [
                'name'=>'expenses.create',
                'guard_name'=>'web',
                'master_name'=>'expenses'
            ],[
                'name'=>'profit-chart.index',
                'guard_name'=>'web',
                'master_name'=>'profit-chart'
            ],[
                'name'=>'billing.master',
                'guard_name'=>'web',
                'master_name'=>'master'
            ],
            
            [
                'name'=>'states.index',
                'guard_name'=>'web',
                'master_name'=>'states'
            ],
            [
                'name'=>'states.create',
                'guard_name'=>'web',
                'master_name'=>'states'
            ],
            [
                'name'=>'states.store',
                'guard_name'=>'web',
                'master_name'=>'states'
            ],
            [
                'name'=>'states.edit',
                'guard_name'=>'web',
                'master_name'=>'states'
            ],
            [
                'name'=>'states.update',
                'guard_name'=>'web',
                'master_name'=>'states'
            ],
            [
                'name'=>'states.destroy',
                'guard_name'=>'web',
                'master_name'=>'states'
            ],


            [
                'name'=>'districts.index',
                'guard_name'=>'web',
                'master_name'=>'districts'
            ],
            [
                'name'=>'districts.create',
                'guard_name'=>'web',
                'master_name'=>'districts'
            ],
            [
                'name'=>'districts.store',
                'guard_name'=>'web',
                'master_name'=>'districts'
            ],
            [
                'name'=>'districts.edit',
                'guard_name'=>'web',
                'master_name'=>'districts'
            ],
            [
                'name'=>'districts.update',
                'guard_name'=>'web',
                'master_name'=>'districts'
            ],
            [
                'name'=>'districts.destroy',
                'guard_name'=>'web',
                'master_name'=>'districts'
            ],
            


            [
                'name'=>'areas.index',
                'guard_name'=>'web',
                'master_name'=>'areas'
            ],
            [
                'name'=>'areas.create',
                'guard_name'=>'web',
                'master_name'=>'areas'
            ],
            [
                'name'=>'areas.store',
                'guard_name'=>'web',
                'master_name'=>'areas'
            ],
            [
                'name'=>'areas.edit',
                'guard_name'=>'web',
                'master_name'=>'areas'
            ],
            [
                'name'=>'areas.update',
                'guard_name'=>'web',
                'master_name'=>'areas'
            ],
            [
                'name'=>'areas.destroy',
                'guard_name'=>'web',
                'master_name'=>'areas'
            ],[
                'name'=>'product_charge.index',
                'guard_name'=>'web',
                'master_name'=>'product_charge'
            ],
            [
                'name'=>'product_charge.create',
                'guard_name'=>'web',
                'master_name'=>'product_charge'
            ],
            [
                'name'=>'product_charge.store',
                'guard_name'=>'web',
                'master_name'=>'product_charge'
            ],
            [
                'name'=>'product_charge.edit',
                'guard_name'=>'web',
                'master_name'=>'product_charge'
            ],
            [
                'name'=>'product_charge.update',
                'guard_name'=>'web',
                'master_name'=>'product_charge'
            ],
            [
                'name'=>'product_charge.destroy',
                'guard_name'=>'web',
                'master_name'=>'product_charge'
            ],
            [
                'name'=>'email-master.index',
                'guard_name'=>'web',
                'master_name'=>'master'
            ],
            [
                'name'=>'sms.master',
                'guard_name'=>'web',
                'master_name'=>'master'
            ],
            [
                'name'=>'general.master',
                'guard_name'=>'web',
                'master_name'=>'master'
            ],[
                'name'=>'purchase-order.index',
                'guard_name'=>'web',
                'master_name'=>'purchase-order'
            ],
            [
                'name'=>'purchase-order.create',
                'guard_name'=>'web',
                'master_name'=>'purchase-order'
            ],
            [
                'name'=>'purchase-order.show',
                'guard_name'=>'web',
                'master_name'=>'purchase-order'
            ],
            [
                'name'=>'purchase-order.destroy',
                'guard_name'=>'web',
                'master_name'=>'purchase-order'
            ],
            [
                'name'=>'purchase-order.store',
                'guard_name'=>'web',
                'master_name'=>'purchase-order'
            ],
            [
                'name'=>'expense-master.index',
                'guard_name'=>'web',
                'master_name'=>'expense-master'
            ],
            [
                'name'=>'expense-master.create',
                'guard_name'=>'web',
                'master_name'=>'expense-master'
            ],
            [
                'name'=>'expense-master.edit',
                'guard_name'=>'web',
                'master_name'=>'expense-master'
            ],
            [
                'name'=>'expense-master.destroy',
                'guard_name'=>'web',
                'master_name'=>'expense-master'
            ],
            [
                'name'=>'expense-master.store',
                'guard_name'=>'web',
                'master_name'=>'expense-master'
            ],
            [
                'name'=>'expense-master.update',
                'guard_name'=>'web',
                'master_name'=>'expense-master'
            ],
            [
                'name'=>'tasks.index',
                'guard_name'=>'web',
                'master_name'=>'tasks'
            ],
            [
                'name'=>'tasks.create',
                'guard_name'=>'web',
                'master_name'=>'tasks'
            ],
            [
                'name'=>'tasks.edit',
                'guard_name'=>'web',
                'master_name'=>'tasks'
            ],
            [
                'name'=>'tasks.destroy',
                'guard_name'=>'web',
                'master_name'=>'tasks'
            ],
            [
                'name'=>'tasks.store',
                'guard_name'=>'web',
                'master_name'=>'tasks'
            ],
            [
                'name'=>'tasks.update',
                'guard_name'=>'web',
                'master_name'=>'tasks'
            ],[
                'name'=>'mytasks.index',
                'guard_name'=>'web',
                'master_name'=>'my-tasks'
            ],
            [
                'name'=>'mytasks.view',
                'guard_name'=>'web',
                'master_name'=>'my-tasks'
            ],
            [
                'name'=>'mytasks.update',
                'guard_name'=>'web',
                'master_name'=>'my-tasks'
            ],[
                'name'=>'payment-gateway.master',
                'guard_name'=>'web',
                'master_name'=>'master'
            ],[
                'name'=>'facebook-page-subscription.master',
                'guard_name'=>'web',
                'master_name'=>'master'
            ],
            [
                'name'=>'leads.index',
                'guard_name'=>'web',
                'master_name'=>'leads'
            ],
            [
                'name'=>'leads.destroy',
                'guard_name'=>'web',
                'master_name'=>'leads'
            ],
            [
                'name'=>'attendance.index',
                'guard_name'=>'web',
                'master_name'=>'attendance'
            ],
            [
                'name'=>'holiday.index',
                'guard_name'=>'web',
                'master_name'=>'holiday'
            ],
            [
                'name'=>'holiday.create',
                'guard_name'=>'web',
                'master_name'=>'holiday'
            ],
            [
                'name'=>'holiday.store',
                'guard_name'=>'web',
                'master_name'=>'holiday'
            ],
            [
                'name'=>'holiday.edit',
                'guard_name'=>'web',
                'master_name'=>'holiday'
            ],
            [
                'name'=>'holiday.update',
                'guard_name'=>'web',
                'master_name'=>'holiday'
            ],
            [
                'name'=>'holiday.destroy',
                'guard_name'=>'web',
                'master_name'=>'holiday'
            ],
            [
                'name'=>'leave.index',
                'guard_name'=>'web',
                'master_name'=>'leave'
            ],
            [
                'name'=>'leave.create',
                'guard_name'=>'web',
                'master_name'=>'leave'
            ],
            [
                'name'=>'leave.store',
                'guard_name'=>'web',
                'master_name'=>'leave'
            ],
            [
                'name'=>'leave.edit',
                'guard_name'=>'web',
                'master_name'=>'leave'
            ],
            [
                'name'=>'leave.update',
                'guard_name'=>'web',
                'master_name'=>'leave'
            ],
            [
                'name'=>'leave.destroy',
                'guard_name'=>'web',
                'master_name'=>'leave'
            ],
            [
                'name'=>'calendar.index',
                'guard_name'=>'web',
                'master_name'=>'calendar'
            ],
            [
                'name'=>'calendar.create',
                'guard_name'=>'web',
                'master_name'=>'calendar'
            ] ,
            [
                'name'=>'calendar.store',
                'guard_name'=>'web',
                'master_name'=>'calendar'
            ] ,
            [
                'name'=>'calendar.edit',
                'guard_name'=>'web',
                'master_name'=>'calendar'
            ] ,
            [
                'name'=>'calendar.update',
                'guard_name'=>'web',
                'master_name'=>'calendar'
            ] ,[
                'name'=>'contract.index',
                'guard_name'=>'web',
                'master_name'=>'contract'
            ],
            [
                'name'=>'contract.create',
                'guard_name'=>'web',
                'master_name'=>'contract'
            ] ,
            [
                'name'=>'contract.store',
                'guard_name'=>'web',
                'master_name'=>'contract'
            ] ,
            [
                'name'=>'contract.edit',
                'guard_name'=>'web',
                'master_name'=>'contract'
            ] ,
            [
                'name'=>'contract.update',
                'guard_name'=>'web',
                'master_name'=>'contract'
            ] ,
            
            [
                'name'=>'contract.delete',
                'guard_name'=>'web',
                'master_name'=>'contract'
            ] ,
            [
                'name'=>'contract-type.index',
                'guard_name'=>'web',
                'master_name'=>'contract-type'
            ],
            [
                'name'=>'contract-type.create',
                'guard_name'=>'web',
                'master_name'=>'contract-type'
            ] ,
            [
                'name'=>'contract-type.store',
                'guard_name'=>'web',
                'master_name'=>'contract-type'
            ] ,
            [
                'name'=>'contract-type.edit',
                'guard_name'=>'web',
                'master_name'=>'contract-type'
            ] ,
            [
                'name'=>'contract-type.update',
                'guard_name'=>'web',
                'master_name'=>'contract-type'
            ] ,
            
            [
                'name'=>'contract-type.delete',
                'guard_name'=>'web',
                'master_name'=>'contract-type'
            ],[
                'name'=>'customers.index',
                'guard_name'=>'web',
                'master_name'=>'customers'
            ],
            [
                'name'=>'customers.create',
                'guard_name'=>'web',
                'master_name'=>'customers'
            ] ,
            [
                'name'=>'customers.store',
                'guard_name'=>'web',
                'master_name'=>'customers'
            ] ,
            [
                'name'=>'customers.edit',
                'guard_name'=>'web',
                'master_name'=>'customers'
            ] ,
            [
                'name'=>'customers.update',
                'guard_name'=>'web',
                'master_name'=>'customers'
            ] ,
            
            [
                'name'=>'customers.delete',
                'guard_name'=>'web',
                'master_name'=>'customers'
            ] ,
            [
                'name'=>'announcements.index',
                'guard_name'=>'web',
                'master_name'=>'announcements'
            ],
            [
                'name'=>'announcements.show',
                'guard_name'=>'web',
                'master_name'=>'announcements'
            ] ,
            [
                'name'=>'announcements.create',
                'guard_name'=>'web',
                'master_name'=>'announcements'
            ] ,
            [
                'name'=>'announcements.store',
                'guard_name'=>'web',
                'master_name'=>'announcements'
            ] ,
            [
                'name'=>'announcements.edit',
                'guard_name'=>'web',
                'master_name'=>'announcements'
            ] ,
            [
                'name'=>'announcements.update',
                'guard_name'=>'web',
                'master_name'=>'announcements'
            ] ,
            
            [
                'name'=>'announcements.delete',
                'guard_name'=>'web',
                'master_name'=>'announcements'
            ],
            [
                'name'=>'backup.index',
                'guard_name'=>'web',
                'master_name'=>'backup'
            ],
            [
                'name'=>'backup.create',
                'guard_name'=>'web',
                'master_name'=>'backup'
            ],
            [
                'name'=>'backup.delete',
                'guard_name'=>'web',
                'master_name'=>'backup'
            ],
            [
                'name'=>'lead-sources.index',
                'guard_name'=>'web',
                'master_name'=>'lead-sources'
            ],
            [
                'name'=>'lead-sources.store',
                'guard_name'=>'web',
                'master_name'=>'lead-sources'
            ],
            [
                'name'=>'lead-sources.edit',
                'guard_name'=>'web',
                'master_name'=>'lead-sources'
            ],
            [
                'name'=>'lead-sources.update',
                'guard_name'=>'web',
                'master_name'=>'lead-sources'
            ],
            [
                'name'=>'lead-sources.destroy',
                'guard_name'=>'web',
                'master_name'=>'lead-sources'
            ],[
                'name'=>'lead-status.index',
                'guard_name'=>'web',
                'master_name'=>'lead-status'
            ],
            [
                'name'=>'lead-status.store',
                'guard_name'=>'web',
                'master_name'=>'lead-status'
            ],
            [
                'name'=>'lead-status.edit',
                'guard_name'=>'web',
                'master_name'=>'lead-status'
            ],
            [
                'name'=>'lead-status.update',
                'guard_name'=>'web',
                'master_name'=>'lead-status'
            ],
            [
                'name'=>'lead-status.destroy',
                'guard_name'=>'web',
                'master_name'=>'lead-status'
            ],[
                'name'=>'lead-status.create',
                'guard_name'=>'web',
                'master_name'=>'lead-status'
            ],[
                'name'=>'lead-sources.create',
                'guard_name'=>'web',
                'master_name'=>'lead-sources'
            ], [
                'name'=>'leads.create',
                'guard_name'=>'web',
                'master_name'=>'leads'
            ],
            [
                'name'=>'leads.store',
                'guard_name'=>'web',
                'master_name'=>'leads'
            ],
            [
                'name'=>'leads.edit',
                'guard_name'=>'web',
                'master_name'=>'leads'
            ],
            [
                'name'=>'leads.update',
                'guard_name'=>'web',
                'master_name'=>'leads'
            ],[
                'name' => 'reports.sales.index',
                'guard_name' => 'web',
                'master_name' => 'reports'
            ],[
                'name'=>'proposal-orders.index',
                'guard_name'=>'web',
                'master_name'=>'proposal-order'
            ],
            [
                'name'=>'proposal-orders.create',
                'guard_name'=>'web',
                'master_name'=>'proposal-order'
            ],
            [
                'name'=>'proposal-orders.show',
                'guard_name'=>'web',
                'master_name'=>'proposal-order'
            ],
            
            [
                'name'=>'proposal-orders.destroy',
                'guard_name'=>'web',
                'master_name'=>'proposal-order'
            ],[
                'name'=>'proposal-orders.store',
                'guard_name'=>'web',
                'master_name'=>'proposal-order'
            ],
            */
        $permissions = [
            [
                'name'=>'proposal-orders.edit',
                'guard_name'=>'web',
                'master_name'=>'proposal-order'
            ],
        ];
      
        foreach ($permissions as $permission) {
            Permission::create($permission);
        }
        
    }
}
